/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/procaddress/ProcAddressEmitter.java on Fri Aug 18 15:56:05 CEST 2023 ----! */
/* !---- Java-Unit: [pkg com.jogamp.opencl.llb.impl, cls CLProcAddressTable12], ../build/gensrc/java/com/jogamp/opencl/llb/impl/CLProcAddressTable12.java ----! */

package com.jogamp.opencl.llb.impl;

import com.jogamp.opencl.llb.impl.CLImageFormatImpl;
import com.jogamp.opencl.llb.impl.CLImageDescImpl;
import com.jogamp.opencl.llb.CL12;
import java.security.AccessController;
import java.security.PrivilegedAction;
import com.jogamp.common.nio.PointerBuffer;
import com.jogamp.common.util.LongLongHashMap;
import com.jogamp.opencl.CLErrorHandler;
import com.jogamp.opencl.CLException;
import java.nio.ByteBuffer;
import java.nio.IntBuffer;
import com.jogamp.common.nio.Buffers;
import com.jogamp.gluegen.runtime.ProcAddressTable;
import com.jogamp.common.util.SecurityUtil;

/**
 * This table is a cache of pointers to the dynamically-linkable C library.
 * @see ProcAddressTable
 */
public final class CLProcAddressTable12 extends ProcAddressTable {

  /* pp */ long _addressof_clGetExtensionFunctionAddress;
  /* pp */ long _addressof_clCreateContext;
  /* pp */ long _addressof_clCreateContextFromType;
  /* pp */ long _addressof_clBuildProgram;
  /* pp */ long _addressof_clCompileProgram;
  /* pp */ long _addressof_clLinkProgram;
  /* pp */ long _addressof_clEnqueueNativeKernel;
  /* pp */ long _addressof_clReleaseContext;
  /* pp */ long _addressof_clSetEventCallback;
  /* pp */ long _addressof_clSetMemObjectDestructorCallback;
  /* pp */ long _addressof_clEnqueueMapImage;

  public CLProcAddressTable12(){ super(); }

  public CLProcAddressTable12(com.jogamp.gluegen.runtime.FunctionAddressResolver resolver){ super(resolver); }

  /* pp */ long _addressof_clGetPlatformIDs;
  /* pp */ long _addressof_clGetPlatformInfo;
  /* pp */ long _addressof_clGetDeviceIDs;
  /* pp */ long _addressof_clGetDeviceInfo;
  /* pp */ long _addressof_clCreateSubDevices;
  /* pp */ long _addressof_clRetainDevice;
  /* pp */ long _addressof_clReleaseDevice;
  /* pp */ long _addressof_clRetainContext;
  /* pp */ long _addressof_clGetContextInfo;
  /* pp */ long _addressof_clCreateCommandQueue;
  /* pp */ long _addressof_clRetainCommandQueue;
  /* pp */ long _addressof_clReleaseCommandQueue;
  /* pp */ long _addressof_clGetCommandQueueInfo;
  /* pp */ long _addressof_clCreateBuffer;
  /* pp */ long _addressof_clCreateSubBuffer;
  /* pp */ long _addressof_clCreateImage;
  /* pp */ long _addressof_clRetainMemObject;
  /* pp */ long _addressof_clReleaseMemObject;
  /* pp */ long _addressof_clGetSupportedImageFormats;
  /* pp */ long _addressof_clGetMemObjectInfo;
  /* pp */ long _addressof_clGetImageInfo;
  /* pp */ long _addressof_clCreateSampler;
  /* pp */ long _addressof_clRetainSampler;
  /* pp */ long _addressof_clReleaseSampler;
  /* pp */ long _addressof_clGetSamplerInfo;
  /* pp */ long _addressof_clCreateProgramWithSource;
  /* pp */ long _addressof_clCreateProgramWithBinary;
  /* pp */ long _addressof_clCreateProgramWithBuiltInKernels;
  /* pp */ long _addressof_clRetainProgram;
  /* pp */ long _addressof_clReleaseProgram;
  /* pp */ long _addressof_clUnloadPlatformCompiler;
  /* pp */ long _addressof_clGetProgramInfo;
  /* pp */ long _addressof_clGetProgramBuildInfo;
  /* pp */ long _addressof_clCreateKernel;
  /* pp */ long _addressof_clCreateKernelsInProgram;
  /* pp */ long _addressof_clRetainKernel;
  /* pp */ long _addressof_clReleaseKernel;
  /* pp */ long _addressof_clSetKernelArg;
  /* pp */ long _addressof_clGetKernelInfo;
  /* pp */ long _addressof_clGetKernelArgInfo;
  /* pp */ long _addressof_clGetKernelWorkGroupInfo;
  /* pp */ long _addressof_clWaitForEvents;
  /* pp */ long _addressof_clGetEventInfo;
  /* pp */ long _addressof_clCreateUserEvent;
  /* pp */ long _addressof_clRetainEvent;
  /* pp */ long _addressof_clReleaseEvent;
  /* pp */ long _addressof_clSetUserEventStatus;
  /* pp */ long _addressof_clGetEventProfilingInfo;
  /* pp */ long _addressof_clFlush;
  /* pp */ long _addressof_clFinish;
  /* pp */ long _addressof_clEnqueueReadBuffer;
  /* pp */ long _addressof_clEnqueueReadBufferRect;
  /* pp */ long _addressof_clEnqueueWriteBuffer;
  /* pp */ long _addressof_clEnqueueWriteBufferRect;
  /* pp */ long _addressof_clEnqueueFillBuffer;
  /* pp */ long _addressof_clEnqueueCopyBuffer;
  /* pp */ long _addressof_clEnqueueCopyBufferRect;
  /* pp */ long _addressof_clEnqueueReadImage;
  /* pp */ long _addressof_clEnqueueWriteImage;
  /* pp */ long _addressof_clEnqueueFillImage;
  /* pp */ long _addressof_clEnqueueCopyImage;
  /* pp */ long _addressof_clEnqueueCopyImageToBuffer;
  /* pp */ long _addressof_clEnqueueCopyBufferToImage;
  /* pp */ long _addressof_clEnqueueMapBuffer;
  /* pp */ long _addressof_clEnqueueUnmapMemObject;
  /* pp */ long _addressof_clEnqueueMigrateMemObjects;
  /* pp */ long _addressof_clEnqueueNDRangeKernel;
  /* pp */ long _addressof_clEnqueueTask;
  /* pp */ long _addressof_clEnqueueMarkerWithWaitList;
  /* pp */ long _addressof_clEnqueueBarrierWithWaitList;
  /* pp */ long _addressof_clGetExtensionFunctionAddressForPlatform;
  /* pp */ long _addressof_clCreateImage2D;
  /* pp */ long _addressof_clCreateImage3D;
  /* pp */ long _addressof_clEnqueueMarker;
  /* pp */ long _addressof_clEnqueueWaitForEvents;
  /* pp */ long _addressof_clEnqueueBarrier;
  /* pp */ long _addressof_clUnloadCompiler;
  /* pp */ long _addressof_clIcdGetPlatformIDsKHR;
  /* pp */ long _addressof_clTerminateContextKHR;
  /* pp */ long _addressof_clReleaseDeviceEXT;
  /* pp */ long _addressof_clRetainDeviceEXT;
  /* pp */ long _addressof_clCreateSubDevicesEXT;
  /* pp */ long _addressof_clCreateFromGLBuffer;
  /* pp */ long _addressof_clCreateFromGLTexture;
  /* pp */ long _addressof_clCreateFromGLRenderbuffer;
  /* pp */ long _addressof_clGetGLObjectInfo;
  /* pp */ long _addressof_clGetGLTextureInfo;
  /* pp */ long _addressof_clEnqueueAcquireGLObjects;
  /* pp */ long _addressof_clEnqueueReleaseGLObjects;
  /* pp */ long _addressof_clCreateFromGLTexture2D;
  /* pp */ long _addressof_clCreateFromGLTexture3D;
  /* pp */ long _addressof_clGetGLContextInfoKHR;
  /* pp */ long _addressof_clCreateEventFromGLsyncKHR;
} // end of class CLProcAddressTable12
