/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/opengl/GLEmitter.java on Fri Aug 18 14:59:00 CEST 2023 ----! */
/* !---- Java-Unit: [pkg jogamp.opengl.macosx.cgl, cls CGLExtImpl], ../build/jogl/gensrc/classes/jogamp/opengl/macosx/cgl/CGLExtImpl.java ----! */

package jogamp.opengl.macosx.cgl;

import java.util.*;
import com.jogamp.opengl.*;
import com.jogamp.opengl.fixedfunc.*;
import jogamp.opengl.*;
import com.jogamp.gluegen.runtime.*;
import com.jogamp.common.os.*;
import com.jogamp.common.nio.*;
import java.nio.*;
import com.jogamp.common.util.*;
import java.util.Set;
import java.util.Map;
import java.util.HashMap;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;

public class CGLExtImpl implements CGLExt{

  // --- Begin CustomJavaCode .cfg declarations
  public CGLExtImpl(MacOSXCGLContext context) {
    this._context = context; 
  }
  public boolean isFunctionAvailable(String glFunctionName)
  {
    return _context.isFunctionAvailable(glFunctionName);
  }
  public boolean isExtensionAvailable(String glExtensionName)
  {
    return _context.isExtensionAvailable(glExtensionName);
  }
  private MacOSXCGLContext _context;
  // ---- End CustomJavaCode .cfg declarations
} // end of class CGLExtImpl
