/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/JavaEmitter.java on Fri Aug 18 14:57:08 CEST 2023 ----! */
/* !---- Java-Unit: [pkg jogamp.nativewindow.jawt.macosx, cls JAWT_MacOSXDrawingSurfaceInfo], ../build/nativewindow/gensrc/classes/jogamp/nativewindow/jawt/macosx/JAWT_MacOSXDrawingSurfaceInfo.java ----! */


package jogamp.nativewindow.jawt.macosx;

import java.nio.*;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;

import com.jogamp.gluegen.runtime.*;
import com.jogamp.common.os.*;
import com.jogamp.common.nio.*;
import jogamp.common.os.MachineDataInfoRuntime;

import java.security.*;
import jogamp.nativewindow.jawt.*;
import com.jogamp.common.os.Platform;
import com.jogamp.common.util.VersionNumber;
import com.jogamp.common.util.SecurityUtil;

public class JAWT_MacOSXDrawingSurfaceInfo implements JAWT_PlatformInfo {

  StructAccessor accessor;

  private static final int mdIdx = MachineDataInfoRuntime.getStatic().ordinal();
  private final MachineDataInfo md;

  private static final int[] JAWT_MacOSXDrawingSurfaceInfo_size = new int[] { 4 /* ARM_MIPS_32 */, 4 /* X86_32_UNIX */, 4 /* X86_32_ANDROID */, 4 /* X86_32_MACOS */, 4 /* PPC_32_UNIX */, 4 /* SPARC_32_SUNOS */, 4 /* X86_32_WINDOWS */, 8 /* LP64_UNIX */, 8 /* X86_64_WINDOWS */, 8 /* ARM64_IOS */  };
  private static final int[] cocoaViewRef_offset = new int[] { 0 /* ARM_MIPS_32 */, 0 /* X86_32_UNIX */, 0 /* X86_32_ANDROID */, 0 /* X86_32_MACOS */, 0 /* PPC_32_UNIX */, 0 /* SPARC_32_SUNOS */, 0 /* X86_32_WINDOWS */, 0 /* LP64_UNIX */, 0 /* X86_64_WINDOWS */, 0 /* ARM64_IOS */ };
//private static final int[] cocoaViewRef_size = new int[] { 4 /* ARM_MIPS_32 */, 4 /* X86_32_UNIX */, 4 /* X86_32_ANDROID */, 4 /* X86_32_MACOS */, 4 /* PPC_32_UNIX */, 4 /* SPARC_32_SUNOS */, 4 /* X86_32_WINDOWS */, 8 /* LP64_UNIX */, 8 /* X86_64_WINDOWS */, 8 /* ARM64_IOS */  };

  /** Returns true if this generated implementation uses native code, otherwise false. */
  public static boolean usesNativeCode() {
    return false;
  }

  /** Returns the aligned total size of a native instance. */
  public static int size() {
    return JAWT_MacOSXDrawingSurfaceInfo_size[mdIdx];
  }

  /** Returns a new instance with all bytes set to zero. */
  public static JAWT_MacOSXDrawingSurfaceInfo create() {
    return create(Buffers.newDirectByteBuffer(size()));
  }

  /** Returns a new instance using the given ByteBuffer having at least {#link size()} bytes capacity. The ByteBuffer will be {@link ByteBuffer#rewind()} and native-order set. */
  public static JAWT_MacOSXDrawingSurfaceInfo create(java.nio.ByteBuffer buf) {
      return new JAWT_MacOSXDrawingSurfaceInfo(buf);
  }

  /** Returns new instance dereferencing ByteBuffer at given native address `addr` with size {@link #size()}. */
  public static JAWT_MacOSXDrawingSurfaceInfo derefPointer(final long addr) {
      return create( ElementBuffer.derefPointer(size(), addr, 1).getByteBuffer() );
  }

  JAWT_MacOSXDrawingSurfaceInfo(java.nio.ByteBuffer buf) {
    md = MachineDataInfo.StaticConfig.values()[mdIdx].md;
    accessor = new StructAccessor(buf);
  }

  /** Return the underlying native direct ByteBuffer */
  public final java.nio.ByteBuffer getBuffer() {
    return accessor.getBuffer();
  }

  /** Returns the native address of the underlying native ByteBuffer {@link #getBuffer()} */
  public final long getDirectBufferAddress() {
    return accessor.getDirectBufferAddress();
  }


  /** SKIP setter for immutable native field <code>cocoaViewRef</code>, referencing a <i>struct</i> owned array with fixed element count of <code>1</code> elements. Maximum element count is <code>1</code>. NativeSig <code>(PointerType) 'NSView *' -> (NSView) * , size[fixed false, lnx64 8], const[false], is[pointer*1]</code>  */

  /**
   * Getter for native field <code>cocoaViewRef</code>, referencing a <i>struct</i> owned array with fixed element count of <code>1</code> elements.
   * <p>
   * Maximum element count is <code>1</code>.
   * </p>
   * <p>
   * Native Signature:
   * <ul>
   *   <li>field-type <code>(PointerType) 'NSView *' -> (NSView) * , size[fixed false, lnx64 8], const[false], is[pointer*1]</code></li>
   *   <li>referenced <code>(StructType) typedef 'NSView', size[fixed false, lnx64 0], const[false], is[struct{_NSView: 0}]</code></li>
   * </ul>
   * </p>
   * @return element value of the corresponding field-array
   */
  public final long getCocoaViewRef() {
    return PointerBuffer.wrap(getBuffer(), cocoaViewRef_offset[mdIdx], 1).get(0);
  }

}
