/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/JavaEmitter.java on Fri Aug 18 14:57:06 CEST 2023 ----! */
/* !---- Java-Unit: [pkg jogamp.nativewindow.windows, cls RGBQUAD], ../build/nativewindow/gensrc/classes/jogamp/nativewindow/windows/RGBQUAD.java ----! */


package jogamp.nativewindow.windows;

import java.nio.*;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;

import com.jogamp.gluegen.runtime.*;
import com.jogamp.common.os.*;
import com.jogamp.common.nio.*;
import jogamp.common.os.MachineDataInfoRuntime;

import com.jogamp.nativewindow.util.Point;
import com.jogamp.nativewindow.NativeWindowException;
import jogamp.nativewindow.NWJNILibLoader;
import jogamp.nativewindow.Debug;

public class RGBQUAD {

  StructAccessor accessor;

  private static final int mdIdx = MachineDataInfoRuntime.getStatic().ordinal();
  private final MachineDataInfo md;

  private static final int[] RGBQUAD_size = new int[] { 4 /* ARM_MIPS_32 */, 4 /* X86_32_UNIX */, 4 /* X86_32_ANDROID */, 4 /* X86_32_MACOS */, 4 /* PPC_32_UNIX */, 4 /* SPARC_32_SUNOS */, 4 /* X86_32_WINDOWS */, 4 /* LP64_UNIX */, 4 /* X86_64_WINDOWS */, 4 /* ARM64_IOS */  };
  private static final int[] rgbBlue_offset = new int[] { 0 /* ARM_MIPS_32 */, 0 /* X86_32_UNIX */, 0 /* X86_32_ANDROID */, 0 /* X86_32_MACOS */, 0 /* PPC_32_UNIX */, 0 /* SPARC_32_SUNOS */, 0 /* X86_32_WINDOWS */, 0 /* LP64_UNIX */, 0 /* X86_64_WINDOWS */, 0 /* ARM64_IOS */ };
//private static final int[] rgbBlue_size = new int[] { 1 /* ARM_MIPS_32 */, 1 /* X86_32_UNIX */, 1 /* X86_32_ANDROID */, 1 /* X86_32_MACOS */, 1 /* PPC_32_UNIX */, 1 /* SPARC_32_SUNOS */, 1 /* X86_32_WINDOWS */, 1 /* LP64_UNIX */, 1 /* X86_64_WINDOWS */, 1 /* ARM64_IOS */  };
  private static final int[] rgbGreen_offset = new int[] { 1 /* ARM_MIPS_32 */, 1 /* X86_32_UNIX */, 1 /* X86_32_ANDROID */, 1 /* X86_32_MACOS */, 1 /* PPC_32_UNIX */, 1 /* SPARC_32_SUNOS */, 1 /* X86_32_WINDOWS */, 1 /* LP64_UNIX */, 1 /* X86_64_WINDOWS */, 1 /* ARM64_IOS */ };
//private static final int[] rgbGreen_size = new int[] { 1 /* ARM_MIPS_32 */, 1 /* X86_32_UNIX */, 1 /* X86_32_ANDROID */, 1 /* X86_32_MACOS */, 1 /* PPC_32_UNIX */, 1 /* SPARC_32_SUNOS */, 1 /* X86_32_WINDOWS */, 1 /* LP64_UNIX */, 1 /* X86_64_WINDOWS */, 1 /* ARM64_IOS */  };
  private static final int[] rgbRed_offset = new int[] { 2 /* ARM_MIPS_32 */, 2 /* X86_32_UNIX */, 2 /* X86_32_ANDROID */, 2 /* X86_32_MACOS */, 2 /* PPC_32_UNIX */, 2 /* SPARC_32_SUNOS */, 2 /* X86_32_WINDOWS */, 2 /* LP64_UNIX */, 2 /* X86_64_WINDOWS */, 2 /* ARM64_IOS */ };
//private static final int[] rgbRed_size = new int[] { 1 /* ARM_MIPS_32 */, 1 /* X86_32_UNIX */, 1 /* X86_32_ANDROID */, 1 /* X86_32_MACOS */, 1 /* PPC_32_UNIX */, 1 /* SPARC_32_SUNOS */, 1 /* X86_32_WINDOWS */, 1 /* LP64_UNIX */, 1 /* X86_64_WINDOWS */, 1 /* ARM64_IOS */  };
  private static final int[] rgbReserved_offset = new int[] { 3 /* ARM_MIPS_32 */, 3 /* X86_32_UNIX */, 3 /* X86_32_ANDROID */, 3 /* X86_32_MACOS */, 3 /* PPC_32_UNIX */, 3 /* SPARC_32_SUNOS */, 3 /* X86_32_WINDOWS */, 3 /* LP64_UNIX */, 3 /* X86_64_WINDOWS */, 3 /* ARM64_IOS */ };
//private static final int[] rgbReserved_size = new int[] { 1 /* ARM_MIPS_32 */, 1 /* X86_32_UNIX */, 1 /* X86_32_ANDROID */, 1 /* X86_32_MACOS */, 1 /* PPC_32_UNIX */, 1 /* SPARC_32_SUNOS */, 1 /* X86_32_WINDOWS */, 1 /* LP64_UNIX */, 1 /* X86_64_WINDOWS */, 1 /* ARM64_IOS */  };

  /** Returns true if this generated implementation uses native code, otherwise false. */
  public static boolean usesNativeCode() {
    return false;
  }

  /** Returns the aligned total size of a native instance. */
  public static int size() {
    return RGBQUAD_size[mdIdx];
  }

  /** Returns a new instance with all bytes set to zero. */
  public static RGBQUAD create() {
    return create(Buffers.newDirectByteBuffer(size()));
  }

  /** Returns a new instance using the given ByteBuffer having at least {#link size()} bytes capacity. The ByteBuffer will be {@link ByteBuffer#rewind()} and native-order set. */
  public static RGBQUAD create(java.nio.ByteBuffer buf) {
      return new RGBQUAD(buf);
  }

  /** Returns new instance dereferencing ByteBuffer at given native address `addr` with size {@link #size()}. */
  public static RGBQUAD derefPointer(final long addr) {
      return create( ElementBuffer.derefPointer(size(), addr, 1).getByteBuffer() );
  }

  RGBQUAD(java.nio.ByteBuffer buf) {
    md = MachineDataInfo.StaticConfig.values()[mdIdx].md;
    accessor = new StructAccessor(buf);
  }

  /** Return the underlying native direct ByteBuffer */
  public final java.nio.ByteBuffer getBuffer() {
    return accessor.getBuffer();
  }

  /** Returns the native address of the underlying native ByteBuffer {@link #getBuffer()} */
  public final long getDirectBufferAddress() {
    return accessor.getDirectBufferAddress();
  }

  /**
   * Getter for native field <code>rgbBlue</code>, being a <i>struct</i> owned IntType.
   * <p>
   * Native Field Signature <code>(IntType) typedef 'BYTE', size[fixed true, lnx64 1], const[false], is[primitive, int]</code>
   * </p>
   */
  public final byte getRgbBlue() {
    return accessor.getByteAt(rgbBlue_offset[mdIdx]);
  }

  /**
   * Getter for native field <code>rgbGreen</code>, being a <i>struct</i> owned IntType.
   * <p>
   * Native Field Signature <code>(IntType) typedef 'BYTE', size[fixed true, lnx64 1], const[false], is[primitive, int]</code>
   * </p>
   */
  public final byte getRgbGreen() {
    return accessor.getByteAt(rgbGreen_offset[mdIdx]);
  }

  /**
   * Getter for native field <code>rgbRed</code>, being a <i>struct</i> owned IntType.
   * <p>
   * Native Field Signature <code>(IntType) typedef 'BYTE', size[fixed true, lnx64 1], const[false], is[primitive, int]</code>
   * </p>
   */
  public final byte getRgbRed() {
    return accessor.getByteAt(rgbRed_offset[mdIdx]);
  }

  /**
   * Getter for native field <code>rgbReserved</code>, being a <i>struct</i> owned IntType.
   * <p>
   * Native Field Signature <code>(IntType) typedef 'BYTE', size[fixed true, lnx64 1], const[false], is[primitive, int]</code>
   * </p>
   */
  public final byte getRgbReserved() {
    return accessor.getByteAt(rgbReserved_offset[mdIdx]);
  }

}
